# sample config.yml

models:
  text-embedder:
    repo_id: "immich-app/ViT-L-16-SigLIP-384__webli"
    files:
      - "textual/model.onnx"
      - "textual/tokenizer.json"
      - "textual/tokenizer_config.json"

  image-embedder:
    repo_id: "immich-app/ViT-L-16-SigLIP-384__webli"
    files:
      - "visual/model.onnx"
      - "visual/preprocess_cfg.json"

  tagger:
    repo_id: "SmilingWolf/wd-vit-large-tagger-v3"
    files:
      - "model.onnx"
      - "selected_tags.csv"