version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  milvus:
    ports:
      - "19530:19530"
      - "9091:9091"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    command: npm start
    networks:
      - my_network